viewer/config/routes.rb
Rails.application.routes.draw do

  root 'runs#index'

  resources :runs

end

viewer/app/models/run.rb
class Run < ActiveRecord::Base
end

viewer/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

viewer/app/controllers/runs_controller.rb
class RunsController < ApplicationController
  def index
    @runs = Run.order('date desc, time desc').page params[:page]
    @runs = @runs.where(t: params[:t]) unless params[:t].blank?
    @runs = @runs.where(mu: params[:mu]) unless params[:mu].blank?
    @runs = @runs.where(x0: params[:x0]) unless params[:x0].blank?
    @runs = @runs.where(epsf: params[:epsf]) unless params[:epsf].blank?
    @runs = @runs.where(V: params[:V]) unless params[:V].blank?
    @runs = @runs.where(Uc: params[:Uc]) unless params[:Uc].blank?
    @runs = @runs.where(Uf: params[:Uf]) unless params[:Uf].blank?
    @runs = @runs.where(omega: params[:omega]) unless params[:omega].blank?
    @runs = @runs.where(delta: params[:delta]) unless params[:delta].blank?

    case params[:order]
    when 'tasc'
      @runs = @runs.order('t asc')
    when 'tdesc'
      @runs = @runs.order('t desc')
    when 'muasc'
      @runs = @runs.order('mu asc')
    when 'mudesc'
      @runs = @runs.order('mu desc')
    when 'x0asc'
      @runs = @runs.order('x0 asc')
    when 'x0desc'
      @runs = @runs.order('x0 desc')
    when 'epsfasc'
      @runs = @runs.order('epsf asc')
    when 'epsfdesc'
      @runs = @runs.order('epsf desc')
    when 'Vasc'
      @runs = @runs.order('V asc')
    when 'Vdesc'
      @runs = @runs.order('V desc')
    when 'Ucasc'
      @runs = @runs.order('Uc asc')
    when 'Ucdesc'
      @runs = @runs.order('Uc desc')
    when 'Ufasc'
      @runs = @runs.order('Uf asc')
    when 'Ufdesc'
      @runs = @runs.order('Uf desc')
    when 'omegaasc'
      @runs = @runs.order('omega asc')
    when 'omegadesc'
      @runs = @runs.order('omega desc')
    when 'deltaasc'
      @runs = @runs.order('delta asc')
    when 'deltadesc'
      @runs = @runs.order('delta desc')
    end
  end
end

viewer/app/helpers/application_helper.rb
module ApplicationHelper
end

viewer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Viewer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag 'https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' %>
</head>
<body>

<%= yield %>

</body>
</html>

viewer/app/views/runs/_run.html.erb
$$t=<%= run.t %>$$
$$\mu=<%= run.mu %>$$
$$X_0=<%= run.x0 %>$$
$$\epsilon_f=<%= run.epsf %>$$
$$V=<%= run.V %>$$
$$U_c=<%= run.Uc %>$$
$$U_f=<%= run.Uf %>$$
$$\omega=<%= run.omega %>+<%= run.delta %>i$$
$$date=<%= run.date %>$$
$$time=<%= run.time %>$$<br>
<%= image_tag "2d/#{run.date}#{run.time}.dat.png" %>
<%= image_tag "3d/#{run.date}#{run.time}.dat.png" %>
<hr>

viewer/app/views/runs/index.html.erb
<form action="" method="get">
    <div class="pull-right">
      <input type="radio" name="order" value="tasc">↑
      <input type="radio" name="order" value="tdesc">↓
      <input type="text" name="t" value="" placeholder="t">
      
      <input type="radio" name="order" value="muasc">↑
      <input type="radio" name="order" value="mudesc">↓
      <input type="text" name="mu" value="" placeholder="mu">
      
      <input type="radio" name="order" value="x0asc">↑
      <input type="radio" name="order" value="x0desc">↓
      <input type="text" name="x0" value="" placeholder="x0">
      
      <input type="radio" name="order" value="epsfasc">↑
      <input type="radio" name="order" value="epsfdesc">↓
      <input type="text" name="epsf" value="" placeholder="epsf">
      
      <input type="radio" name="order" value="Vasc">↑
      <input type="radio" name="order" value="Vdesc">↓
      <input type="text" name="V" value="" placeholder="V">
      
      <input type="radio" name="order" value="Ucasc">↑
      <input type="radio" name="order" value="Ucdesc">↓
      <input type="text" name="Uc" value="" placeholder="Uc">
      
      <input type="radio" name="order" value="Ufasc">↑
      <input type="radio" name="order" value="Ufdesc">↓
      <input type="text" name="Uf" value="" placeholder="Uf">
      
      <input type="radio" name="order" value="omegaasc">↑
      <input type="radio" name="order" value="omegadesc">↓
      <input type="text" name="omega" value="" placeholder="omega">
      
      <input type="radio" name="order" value="deltaasc">↑
      <input type="radio" name="order" value="deltadesc">↓
      <input type="text" name="delta" value="" placeholder="delta">

      <button type="submit" class="btn btn-primary">OK</button>
      <%= link_to "clear", runs_path %>
    </div>
  </form>
<hr>
<%= render @runs %>
<%= paginate @runs %>